Adding Universal Pages in FoodAdvisor Frontend
strapi/foodadvisor pull request #67
Opened 2020-12-18 19:27 UTC by malgamves

Still a draft pr

2021-01-04 14:32 UTC, soupette requested changes

2021-01-04 14:32 UTC, soupette commented on client/src/containers/App/index.js
> +        <Route path="/:title" component={UniversalPage} exact />
Can you use `slug` instead of `title` ?

2021-01-05 08:59 UTC, malgamves commented
Working on the changes! Thanks for the tips

2021-01-05 09:32 UTC, malgamves commented on client/src/containers/UniversalPage/tests/index.test.js
> +    shallow(<UniversalPage />);
sure thing, changing the `title` to `slug` also

2021-01-18 14:57 UTC, Mcastres commented on api/components/footer/columns.json
> +    "link": {
LGTM

2021-01-18 14:58 UTC, Mcastres commented on client/src/components/FooterColumn/tests/index.test.js
> +// import React from 'react';
LGTM

2021-01-18 14:58 UTC, Mcastres commented on client/src/queries/footer.js
> +query newFooter {
LGTM

2021-01-18 14:59 UTC, Mcastres commented on client/src/components/FooterColumn/index.js
> +FooterColumn.propTypes = {};
LGTM

2021-01-18 14:59 UTC, Mcastres commented on client/src/components/FooterColumn/Column.js
> +export default Column;
LGTM

2021-01-18 15:00 UTC, Mcastres commented on client/src/components/Footer/tests/index.test.js
> +    shallow(<Footer match={{ params: { columns: [] } }} />);
Deleted, LGTM

2021-01-18 15:01 UTC, Mcastres commented on client/src/components/Footer/index.js
> +  onSubmit: e => e.preventDefault(),
LGTM

2021-01-18 15:01 UTC, Mcastres commented on client/src/components/Footer/index.js
> +  onSubmit: e => e.preventDefault(),
LGTM

2021-01-18 15:01 UTC, Mcastres approved these changes
LGTM

2021-01-18 15:14 UTC, Mcastres approved these changes
LGTM

2021-01-21 13:27 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/foodadvisor?pullRequest=67) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.strapi.io/strapi/foodadvisor?pullRequest=67) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: malgamves<br/>:x: lauriejim<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/foodadvisor?pullRequest=67) it.</sub>

2021-01-26 07:27 UTC, soupette requested changes

2021-01-26 07:27 UTC, soupette commented on client/src/components/Footer/index.js
> +  columns: PropTypes.array,
`columns: PropTypes.array.isRequired`

2021-01-26 07:27 UTC, soupette commented on client/src/components/FooterColumn/index.js
> +  column:[],
This should be `columns`

2021-01-26 09:36 UTC, soupette approved these changes
LGTM

2021-01-26 14:40 UTC, merged